### ISSUE TITLE
PCF8574 problem podczas kompilacji

### ISSUE THREAD

**Issue by Eugeniusz195810** [RobTillaart/PCF8574#46]
![Zrzut ekranu 2023-12-31 132552](https://github.com/RobTillaart/PCF8575/assets/126965848/cab12910-bd5d-4f56-9f70-ae4bb3ac2e66)

**Comment by RobTillaart** [comment]
Sorry answered wrong issue (deleted)

-----

My PCF8574 library has no **pinMode()** function as it needs not to be set.

This is different from some other IO expanders e.g. MCP23017 which do have a **pinMode()**.

So just leave out the line and it should work.

**Comment by RobTillaart** [comment]
Any progress to report?

**Comment by RobTillaart** [comment]
The adafruit pcf8574 library apparently has another interface that does support the pinMode command.
It probably does write a 0 or 1 to the device to simulate a pull up. 
My library has no pinMode command but just uses the write command directly.
Note that the device has no DDR ==DataDirectionRegister.

If the adafruit lib works for you I assume your problem is solved and you may close the issue.

**Comment by Eugeniusz195810** [comment]
<img width="439" alt="image" src="https://github.com/RobTillaart/PCF8574/assets/126965848/1bb20bad-c4de-4dc4-8bb3-60ab1dc4e251">
![1704460327517](https://github.com/RobTillaart/PCF8574/assets/126965848/255dd5b8-1999-4025-b784-5a9f6104a564)

**Comment by Eugeniusz195810** [comment]
![Uploading 1704460327517.jpg…]()

**Comment by RobTillaart** [comment]
Have a look at the examples to see how to use the library.

Thanks for trying.
